name: CD

on:
  push:
    branches: [ master ] # Change this to the branch you want to deploy from (e.g., dev)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Save the SSH key to a file
          echo "$EC2_SSH_KEY" > fastapi-blogs-app.pem
          chmod 600 fastapi-blogs-app.pem

          # Connect to EC2 and deploy
          ssh -i fastapi-blogs-app.pem $EC2_USER@ec2-$EC2_HOST.ap-southeast-1.compute.amazonaws.com << 'EOF'
            # Navigate to your app directory
            cd FastAPI-SQLAlchemy  # Change this to your app's path

            # Pull the latest changes from your repository
            git pull origin master # Change this to the branch you are deploying from

            # Create virtual environment
            python3 -m venv venv

            # Activate virtual environtment
            source venv/bin/activate

            # Install or update your Python dependencies
            pip install -r requirements.txt

            # Restart your FastAPI application (assuming you use Uvicorn or Gunicorn)
            # If you are using a service manager like systemd, use systemctl restart
            # Example for Uvicorn:
            python3 main.py
          EOF

          # Clean up the SSH key file
          rm fastapi-blogs-appp.pem
