name: CI

on:
  push:
    branches:
      - dev  # Trigger on pushes to the dev branch
      - main # You can keep main if you also want to trigger on it
  pull_request:
    branches:
      - dev  # Trigger on PRs targeting the dev branch
      - main # You can keep main if you also want to trigger on it

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/  # Run your tests here
